eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:7000/eureka}

spring.datasource.url=postgresql://localhost:5432/subscriptions_and_payments
spring.datasource.username=given
spring.datasource.password=password
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true